# This file was generated by GoReleaser. DO NOT EDIT.
cask "xpose" do
  name "xpose"
  desc "Expose local servers to the internet via Cloudflare"
  homepage "https://xpose.dev"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xpose"

  on_macos do
    on_intel do
      url "https://github.com/nkootstra/xpose/releases/download/v#{version}/xpose_darwin_amd64.tar.gz"
      sha256 "b5ea8596f3842b380904460b6cc270cbd6ec41f38acf733c4e8211e3093e8c5c"
    end
    on_arm do
      url "https://github.com/nkootstra/xpose/releases/download/v#{version}/xpose_darwin_arm64.tar.gz"
      sha256 "1a4f33a4b3a1b6f9669fa65a3e090b8979b2b140c5f5396502e5348f947b12de"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nkootstra/xpose/releases/download/v#{version}/xpose_linux_amd64.tar.gz"
      sha256 "feca4a202adaf45bad9a7208cd6b4690e735a1505cbde806871c39d70afb9ae8"
    end
    on_arm do
      url "https://github.com/nkootstra/xpose/releases/download/v#{version}/xpose_linux_arm64.tar.gz"
      sha256 "365148d4c64c740f364570ccc44e23a59b83c34f3452c2656842139ab4322aee"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xpose"]
    end
  end

  # No zap stanza required
end
